lab1 report vbox version
ch4t5ky/2023_2024-openstack-teamwork pull request #1
Opened 2024-03-04 07:25 UTC by Korpenter

2024-03-04 07:33 UTC, ch4t5ky commented
Переименую в README.md, тогда при входе в папку сразу отчет будет виден

2024-03-04 11:56 UTC, Ishuachka approved these changes

2024-03-04 13:46 UTC, Korpenter commented
> Переименуй в README.md, тогда при входе в папку сразу отчет будет виден

Done

2024-03-05 16:18 UTC, ch4t5ky commented on lab1/README.md
> +Также для виртуальном машины пробрасываются порты для дальнейшего управления по shh, и доступа к ui openstack:
shh - мощный сервис

2024-03-05 17:37 UTC, Korpenter commented on lab1/README.md
> +Также для виртуальном машины пробрасываются порты для дальнейшего управления по shh, и доступа к ui openstack:
![image](https://github.com/ch4t5ky/2023_2024-openstack-teamwork/assets/141184937/a8698b96-9c05-460c-800f-df4a6c6fd96e)

2024-03-05 17:39 UTC, ch4t5ky commented on lab1/README.md
> +#####`Из-за неудобства работы с VirtualBox было решено настроить VS Code для работы с ВМ по ssh, и zsh`
а зачем h5 тебе?

2024-03-05 17:50 UTC, ch4t5ky requested changes

2024-03-05 17:50 UTC, ch4t5ky commented on lab1/README.md
> +## Лабораторная работа №1 "Подготовка к развертыванию OpenStack"
```suggestion
# Лабораторная работа №1 "Подготовка к развертыванию OpenStack"
```

2024-03-05 17:50 UTC, ch4t5ky commented on lab1/README.md
> +#### Введение
```suggestion
## Введение
```

2024-03-05 17:50 UTC, ch4t5ky commented on lab1/README.md
> +#### Ход выполнения работы
```suggestion
## Ход выполнения работы
```

2024-03-05 17:50 UTC, ch4t5ky commented on lab1/README.md
> +#####`Из-за неудобства работы с VirtualBox было решено настроить VS Code для работы с ВМ по ssh, и zsh`
```suggestion
`Из-за неудобства работы с VirtualBox было решено настроить VS Code для работы с ВМ по ssh, и zsh`
```

2024-03-05 17:52 UTC, Korpenter commented on lab1/README.md
> +## Лабораторная работа №1 "Подготовка к развертыванию OpenStack"
Этот человек любит большие буквы

2024-03-05 17:55 UTC, Korpenter commented on lab1/README.md
> +#####`Из-за неудобства работы с VirtualBox было решено настроить VS Code для работы с ВМ по ssh, и zsh`
github не умеет в жир

2024-03-05 17:58 UTC, ch4t5ky approved these changes

2024-03-05 18:07 UTC, merged